-- MySQL Script generated by MySQL Workbench
-- Sat Nov  2 13:34:10 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hostalDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hostalDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hostalDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_danish_ci ;
USE `hostalDB` ;

-- -----------------------------------------------------
-- Table `hostalDB`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hostalDB`.`room` (
  `roomNo` INT NOT NULL,
  PRIMARY KEY (`roomNo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hostalDB`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hostalDB`.`student` (
  `studentID` INT NOT NULL,
  `studentName` VARCHAR(45) NOT NULL,
  `nic` VARCHAR(45) NOT NULL,
  `batch` VARCHAR(45) NULL,
  `phoneNumber` INT(10) NOT NULL,
  `pswd` VARCHAR(45) NOT NULL,
  `stRoomNo` INT NOT NULL,
  PRIMARY KEY (`studentID`),
  CONSTRAINT `fk_student_room1`
    FOREIGN KEY (`stRoomNo`)
    REFERENCES `hostalDB`.`room` (`roomNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hostalDB`.`InOut_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hostalDB`.`InOut_table` (
  `student_studentID` INT NOT NULL,
  `status` BINARY(1) NULL DEFAULT 1,
  `dateTime` DATETIME NULL,
  `note` MEDIUMTEXT NULL,
  PRIMARY KEY (`student_studentID`),
  CONSTRAINT `fk_InOut_table_student1`
    FOREIGN KEY (`student_studentID`)
    REFERENCES `hostalDB`.`student` (`studentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hostalDB`.`chair`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hostalDB`.`chair` (
  `chairID` VARCHAR(45) NOT NULL,
  `demageState` VARCHAR(45) NULL,
  `roomNo` INT NULL,
  `room_roomNo` INT NOT NULL,
  PRIMARY KEY (`chairID`),
  CONSTRAINT `fk_chair_room1`
    FOREIGN KEY (`room_roomNo`)
    REFERENCES `hostalDB`.`room` (`roomNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hostalDB`.`bed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hostalDB`.`bed` (
  `bedID` VARCHAR(45) NOT NULL,
  `demageState` VARCHAR(45) NULL,
  `roomNo` INT NULL,
  `room_roomNo` INT NOT NULL,
  PRIMARY KEY (`bedID`),
  CONSTRAINT `fk_bed_room1`
    FOREIGN KEY (`room_roomNo`)
    REFERENCES `hostalDB`.`room` (`roomNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hostalDB`.`desk`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hostalDB`.`desk` (
  `deskID` VARCHAR(45) NOT NULL,
  `demageState` VARCHAR(45) NULL,
  `roomNo` INT NULL,
  `room_roomNo` INT NOT NULL,
  PRIMARY KEY (`deskID`),
  CONSTRAINT `fk_desk_room1`
    FOREIGN KEY (`room_roomNo`)
    REFERENCES `hostalDB`.`room` (`roomNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hostalDB`.`mettress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hostalDB`.`mettress` (
  `mettressID` VARCHAR(45) NOT NULL,
  `demageState` VARCHAR(45) NULL,
  `roomNo` INT NULL,
  `room_roomNo` INT NOT NULL,
  PRIMARY KEY (`mettressID`),
  CONSTRAINT `fk_mettress_room1`
    FOREIGN KEY (`room_roomNo`)
    REFERENCES `hostalDB`.`room` (`roomNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hostalDB`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hostalDB`.`admin` (
  `username` INT NOT NULL,
  `password` VARCHAR(45) NULL,
  `nic` VARCHAR(45) NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hostalDB`.`securityPerson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hostalDB`.`securityPerson` (
  `securityPersonID` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`securityPersonID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hostalDB`.`securityPersonInOut`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hostalDB`.`securityPersonInOut` (
  `securityPersonID` VARCHAR(45) NOT NULL,
  `status` BINARY(1) NULL,
  `note` MEDIUMTEXT NULL,
  `time` DATETIME NULL,
  PRIMARY KEY (`securityPersonID`),
  CONSTRAINT `fk_securityPersonInOut_securityPerson1`
    FOREIGN KEY (`securityPersonID`)
    REFERENCES `hostalDB`.`securityPerson` (`securityPersonID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
